---
- name: launch boshlite box
  hosts: local
  gather_facts: false
  vars:
    keypair: juju
    instance_type: m3.xlarge
    security_group: cf-pipeline-boshlite
    region: us-east-1
    secdesc: For cf-juju package exports
  tasks:
  # necessary due to bug in ec2_group
  - name: check sec group
    local_action:
      module: ec2_group
      name: "{{ security_group }}"
      description: "{{ secdesc }}"
      state: present
      region: "{{ region }}"
    register: sec_group
    ignore_errors: true

  - name: security group
    local_action:
      module: ec2_group
      name: "{{ security_group }}"
      description: "{{ secdesc }}"
      region: "{{ region }}"
      state: present
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 10.0.0.0/0
      rules_egress:
        - proto: all
          from_port: all
          to_port: all
          cidr_ip: 10.0.0.0/0

  - name: fetch ami
    local_action:
      module: script ami.sh
      executable: /bin/bash
    register: fetch_ami

  - set_fact:
      image: "{{fetch_ami.stdout | trim}}"

  - name: Launch boshlite instance
    local_action:
      module: ec2
      key_name: "{{ keypair }}"
      group: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: true
      state: present
      region: "{{ region }}"
      id: "boshlite-cf-export-c"
      volumes:
        - device_name: /dev/sda1
          volume_size: 50
          delete_on_termination: true
    register: ec2

  - name: Add bl instance to host group
    local_action: add_host hostname={{ item.public_ip }} groupname=blbox
    with_items: ec2.instances

  - name: Wait for SSH to come up
    local_action:
      module: wait_for
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: ec2.instances
    #when: not (item.state == 'running')

- include: boshlite.yml