---
# Does a package release for existing bare boshlite instance
# see: run-bl.sh
- name: Do Package Release (RAW)
  hosts: blbox
  remote_user: ubuntu
  vars_files:
    - ./vars/base-vars.yml
    - ./vars/run-vars.yml
  tasks:
    - include: tasks/export-packages.yml
